TAG: "&a[&7SmartAdmin&a]"
TAG_ERROR: "&4[&7SmartAdmin&4]"
TAG_ANTYCHEAT: "&6[&eSmartAdmin&6]"
JOIN_MESSAGE: "&a{player} &7joined the game"
LEAVE_MESSAGE: "&a{player} &7left the game"
FULL_SERVER_MESSAGE: "&cThe server is full!"
MAX_PLAYERS: true