name: SmartAdmin
version: 0.1
main: com.gmail.kukubaczek.SmartAdmin.Main
description: "Wprowadza na Twój serwer autorskie Toolsy! Wystarczy wpisać /smartadmin open!"
authors: [Kukubaczek, JuniorJPDJ]
database: false

commands:
  smartadmin:
    description: Otwiera panel zarzadzania serwerem.
  kick:
    description: Wyrzuca gracza z serwera.
  kickall:
    description: Wyrzuca wszystkich graczy z serwera.
  helpop:
    description: Wysyla wiadomosc do administracji.
    
permissions:
  SmartAdmin.*:
    default: op