name: SmartAdmin
version: 0.1
main: com.gmail.kukubaczek.SmartAdmin.Main
description: "Wprowadza na Twój serwer autorskie Toolsy! Wystarczy wpisać /smartadmin open!"
authors: [Kukubaczek, JuniorJPDJ]
database: false

commands:
  smartadmin:
    description: Otwiera panel zarzadzania serwerem.
    aliases: [sa, smartadm, sadmin]
  kick:
    description: Wyrzuca gracza z serwera.
  kickall:
    description: Wyrzuca wszystkich graczy z serwera.
  helpop:
    description: Wysyla wiadomosc do administracji.
  endersee:
    description: Pokazuje enderchest gracza.
  invsee:
    description: Pokazuje ekwipunek gracza.
  ClearInv:
    description: Czysci ekwipunek.
    aliases: [cinv, ci]
  gamemode:
    description: Zmienia tryb gry.
    usage: /<command> [tryb gry] [gracz]
    aliases: [gm]
    
permissions:
  SmartAdmin.*:
    default: op
    children:
      SmartAdmin.AntyCheat: true