name: SmartAdmin
version: 0.1
main: com.gmail.kukubaczek.SmartAdmin.Main

commands:
  smartadmin:
    description: Otwiera panel zarzadzania serwerem.
  kick:
    description: Wyrzuca gracza z serwera.
  kickall:
    description: Wyrzuca wszystkich graczy z serwera.